-- AlterEnum: Add BUSINESS_OWNER and CUSTOMER to UserRole
ALTER TABLE `users` MODIFY COLUMN `role` ENUM('SUPER_ADMIN', 'BRAND_MANAGER', 'BRANCH_ADMIN', 'EXECUTIVE', 'BUSINESS_OWNER', 'CUSTOMER') NOT NULL DEFAULT 'BRANCH_ADMIN';
